---
language: ruby
before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/stable -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential ruby-dev lxc-dev
gemfile:
  - .gemfile
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.6"
notifications:
  email: false
