HOSTS:
  ubuntu-server-1404-x64:
    roles:
      - default
    platform: ubuntu-14.04-amd64
    box : puppetlabs/ubuntu-14.04-64-puppet
    box_url : https://vagrantcloud.com/puppetlabs/ubuntu-14.04-64-puppet
    hypervisor : vagrant
CONFIG:
  type: foss
